name: Docker Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Docker image
        run: |
          ./gradlew bootBuildImage \
            --imageName=asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/wishbone:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/wishbone:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_APP_NAME }} \
            --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/wishbone:${{ github.sha }} \
            --platform managed \
            --region asia-northeast3
